using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Tenant.API.Base.Repository;
using Tenant.Query.Context.Authentication;
using static System.Runtime.InteropServices.JavaScript.JSType;
using static Tenant.API.Base.Core.Constant.SecretManager;

namespace Tenant.Query.Repository.Authentication
{
    public class AuthenticationRepository : TnBaseQueryRepository<Model.Authentication.Authentication, Context.Authentication.AuthenticationContext>
    {
        private readonly IConfiguration _configuration;

        /// <summary>
        /// Initializes a new instance of the <see cref="T:XtraChef.Tenant.Repository.Tenant"/> class.
        /// </summary>
        /// <param name="dbContext">Db context.</param>
        /// <param name="loggerFactory">Logger factory.</param>
        public AuthenticationRepository(Context.Authentication.AuthenticationContext dbContext, ILoggerFactory loggerFactory, IConfiguration configuration) : base(dbContext, loggerFactory)
        {
            this._configuration = configuration;
        }

        public override Task<Model.Authentication.Authentication> GetById(string tenantId, string id)
        {
            throw new NotImplementedException();
        }

        #region Public Methods

        /// <summary>
        /// Validate token context
        /// </summary>
        /// <param name="tenantId"></param>
        /// <param name="locationId"></param>
        /// <param name="userId"></param>
        /// <param name="userRole"></param>
        /// <param name="spName"></param>
        /// <returns></returns>
        public bool ValidateTokenContext(string tenantId, string locationId, string userId, string userRole, string spName)
        {
            try
            {
                SqlParameter Tenant = new SqlParameter
                {
                    ParameterName = "@TENANTID",
                    SqlDbType = SqlDbType.BigInt,
                    Value = Convert.ToInt64(tenantId)
                };

                SqlParameter Location = new SqlParameter
                {
                    ParameterName = "@LOCATIONID",
                    SqlDbType = SqlDbType.BigInt,
                    Value = Convert.ToInt64(locationId)
                };

                SqlParameter User = new SqlParameter
                {
                    ParameterName = "@USERID",
                    SqlDbType = SqlDbType.BigInt,
                    Value = Convert.ToInt64(userId)
                };

                SqlParameter UserRole = new SqlParameter
                {
                    ParameterName = "@USERROLE",
                    SqlDbType = SqlDbType.BigInt,
                    Value = Convert.ToInt64(userRole)
                };

                Model.Authentication.ValidTokenContext result = this.DbContext.ValidTokenContexts.FromSqlRaw($"exec {spName} @TENANTID,@LOCATIONID,@USERID,@USERROLE", Tenant, Location, User, UserRole).AsNoTracking().AsEnumerable().FirstOrDefault();

                return result != null ? result.IsValid : false;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        #endregion
    }
}


//CREATE PROCEDURE [dbo].[XC_VALIDATE_TOKEN_CONTEXT] (
//	@TENANTID BIGINT
//	,@LOCATIONID BIGINT
//	,@USERID BIGINT
//	,@USERROLE BIGINT
//	)
//AS
//BEGIN
//	SET NOCOUNT ON;

//	DECLARE @VALIDTOKEN BIT = 0;

//	IF EXISTS (
//			SELECT 1
//			FROM [dbo].[XC_TENANT] WITH (NOLOCK)
//			WHERE TENANT_ID = @TENANTID
//				AND ACTIVE = 1
//			)
//	BEGIN
//		IF EXISTS (
//				SELECT 1
//				FROM [dbo].[XC_LOCATION] WITH (NOLOCK)
//				WHERE TENENT_ID = @TENANTID
//					AND LOCATION_ID = @LOCATIONID
//					AND ACTIVE = 1
//				)
//			OR @LOCATIONID = 0
//		BEGIN
//			IF EXISTS (
//					SELECT 1
//					FROM [dbo].[XC_USER] WITH (NOLOCK)
//					WHERE TENANT_ID = @TENANTID
//						AND [USER_ID] = @USERID
//						AND ACTIVE = 1
//					)
//			BEGIN
//				IF EXISTS (
//						SELECT 1
//						FROM [dbo].[XC_USER_ROLES] WITH (NOLOCK)
//						WHERE [USER_ID] = @USERID
//							AND ROLE_ID = @USERROLE
//						)
//				BEGIN
//					SET @VALIDTOKEN = 1;
//				END
//				ELSE
//				BEGIN
//					SET @VALIDTOKEN = 0;
//				END
//			END
//			ELSE
//			BEGIN
//				SET @VALIDTOKEN = 0;
//			END
//		END
//		ELSE
//		BEGIN
//			SET @VALIDTOKEN = 0;
//		END
//	END
//	ELSE
//	BEGIN
//		SET @VALIDTOKEN = 0;
//	END

//	SELECT @VALIDTOKEN AS ISVALID;

//	SET NOCOUNT OFF;
//END
//GO



//CREATE PROCEDURE XC_GET_CATEGORY_TEST
//(
//	@TENANT_ID BIGINT
//)
//AS
//BEGIN
//	SELECT 
//	Pk, TenantId, Category, SubCategory, Active 
//	FROM ProductCategory with(nolock)
//END
//GO

//ALTER PROCEDURE[dbo].[XC_GET_TENANT_TESTED]
//(
//    @TENANT_ID BIGINT
//)
//AS
//BEGIN
// SET NOCOUNT ON

// DECLARE 
//	@TENANT_ID_IP BIGINT
//	, @DEFAULT_PRODUCT_DESC_OPTION NVARCHAR(100)

// SELECT @TENANT_ID_IP = @TENANT_ID

// SELECT @DEFAULT_PRODUCT_DESC_OPTION = ISNULL(CONFIGVALUE, 0)
// FROM [dbo].[XC_APPCONFIG] WITH(NOLOCK)
// WHERE CONFIGKEY = 'DEFAULT_PRODUCT_DESC_OPTION'

// DROP TABLE IF EXISTS #CONFIGKEYTABLE
// CREATE TABLE #CONFIGKEYTABLE (ConfigKey NVARCHAR(510) NOT NULL)

// INSERT INTO #CONFIGKEYTABLE
// VALUES (N'ENABLE_PRODUCT_CATALOG_BETA')
//  ,(N'COMPEAT_EXTRACT')
//  ,(N'IMAGE_EXTRACT')
//  ,(N'QUICKBOOK_EXTRACT')
//  ,(N'R365_EXTRACT')
//  ,(N'ENABLE_PRODUCT_THRESHOLD_NOTIFICATION')
//  ,(N'ENABLE_APROVAL')
//  ,(N'PAID_DATE_MANDATORY')
//  ,(N'PAID_AMOUNT_MANDATORY')
//  ,(N'PAYMENT_REFERENCE_NUMBER_MANDATORY')
//  ,(N'MEMO_MANDATORY')
//  ,(N'PAID_AMOUNT_DEFAULT')
//  ,(N'PAID_DATE_DEFAULT')
//  ,(N'ENABLE_DUPLICATE_PRODUCT')
//  ,(N'DISABLE_APPROVAL_EMAIL_NOTIFICATION')
//  ,(N'ENABLE_QUICKBOOKS_LOCATIONINVOICE')
//  ,(N'ENABLE_REPROCESS_INVOICE')
//  ,(N'ENABLE_THIRDPARTY_INTEGRATION_SERVICES')
//  ,(N'INTACCT_JOURNAL_EXTRACT')
//  ,(N'INTACCT_JOURNAL_API_EXTRACT')
//  ,(N'ENABLE_INVENTORY')
//  ,(N'DISABLE_SYSTEMREJECT')
//  ,(N'DISABLE_SYSTEMREJECT_REASON')
//  ,(N'ENABLE_POSTING_DATE')
//  ,(N'POSTING_DATE_PREFERENCE')
//  ,(N'ENABLE_JOURNAL')
//  ,(N'DISCOUNT_BY')
//  ,(N'INV_DUP_WITHINAPPROVAL')
//  ,(N'JOURNAL_POSTING_BY')
//  ,(N'ENABLE_RECIPE')
//  ,(N'ENABLE_RMS_MASTER_CONFIG_SYNC')
//  ,(N'ENABLE_CHANGE_VENDOR_REQUEST')
//  ,(N'ENABLE_BILL_PAY')
//  ,(N'ENABLE_VENDOR_HUB')
//  ,(N'ENROLLED_FOR_XTRACASH')
//  ,(N'REGISTERED_FOR_BUYERS_EDGE')
//  ,(N'PACKAGE_CODE')
//  ,(N'UPLOAD_TRIAL_END_ON')
//  ,(N'SYNC_ENABLE_ACCT_POSTING_FREQUENCY')
//  ,(N'ENABLE_INAPP_NOTIFICATION')
//  ,(N'ENABLE_COSTCENTRE_ALLOCATION_SAVE_TEMPLATE')
//  ,(N'INV_DUP_WITHINCOSTCENTER')
//  ,(N'BILL_PAY_APPROVAL')
//  ,(N'ENABLE_DISCOUNT_BY_REVENUE_CENTER')
//  ,(N'SKIP_INTERNAL_LOCATION_MAPPING')
//  ,(N'QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD')
//  ,(N'ENABLE_CREDIT_COST_CENTER_ALLOCATION')
//  ,(N'ENABLE_CENTRAL_KITCHEN_ORDER_PROCESSING')
//  ,(N'SHOW_VENDOR_CODE_IN_APPROVAL')
//  ,(N'EDIT_PRODUCT_DESCRIPTION')
//  ,(N'PRODUCT_NAME_DISPLAY_OPTIONS')
//  ,(N'ENABLE_MARKET_TRENDS')
//  ,(N'ENABLE_PRODUCT_REVIEW_FOR_EDI_INVOICE')
//  ,(N'ENABLE_PAYROLL')
//  ,(N'WEBHOOKS_QUICKBOOKS_ONLINE_ENABLE')
//  ,(N'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_GL')
//  ,(N'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_CLASSES')
//  ,(N'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_VENDORS')
//  ,(N'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_PAYMENT_TERMS')
//  ,(N'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_BILL_PAYMENT')
//  ,(N'WEBHOOKS_QUICKBOOKS_ONLINE_AUDIT_DATETIME')
//  ,(N'WEBHOOKS_QUICKBOOKS_ONLINE_USER_ID')
//  ,(N'POST_BILLPAY_PAYMENT_TO_ACCT_SYSTEM')
//  ,(N'ENABLE_DRIFT_CHAT')
//  ,(N'BILL_PAY_CUTOFF_DATE')
//  ,(N'AUTO_ASSIGN_INVOICE_ID_FOR_TENANT')
//  ,(N'ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM')
//  ,(N'ENABLE_BOOKS') 
//  ,(N'ENABLE_PREDICTIVE_CATEGORY_MAPPING')
//  ,(N'ENABLE_SKIP_MISSING_VENDOR_CODE_EXCEPTION')
//  ,(N'QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE')
//  ,(N'QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE')
//  ,(N'WHITE_GLOVE_CUSTOMER')
//  ,(N'AUTOCORRECT_PREVIOUS_PURCHASE')

// SELECT TENANT_ID
//  , TENANT_NAME
//  , ISENABLECUSTOMCATEGORY AS [CUSTOM CATEGORY]
//  ,[GUID]
//  ,ACTIVE
//  ,ISNULL(CAST(ENABLE_PRODUCT_CATALOG_BETA AS BIT), 0) AS 'ENABLE_PRODUCT_CATALOG_BETA'
//  , APPLICATION_TYPE
//  , STARTDAY
//  , ISENABLECOST_CENTRE
//  ,CAST(COMPEAT_EXTRACT AS BIT) AS 'ENABLE_EXTRACT'
//  , ENABLE_CREDITENTRY
//  ,CAST(IMAGE_EXTRACT AS BIT) AS 'ENABLE_EXTRACT_IMAGES'
//  ,CAST(QUICKBOOK_EXTRACT AS BIT) AS 'ENABLE_EXTRACT_QUICKBOOK'
//  ,CAST(R365_EXTRACT AS BIT) AS 'ENABLE_EXTRACT_R365'
//  ,ISNULL(GROUP_ID, 0) AS 'GROUP_ID'
//  ,ISNULL(ACCOUNT_MANAGER, '') AS 'ACCOUNT_MANAGER'
//  ,CONCAT(ISNULL(FIRST_NAME, ACCOUNT_MANAGER),' ',ISNULL(LAST_NAME,'')) AS 'MANAGER_NAME'
//  ,CONCAT (
//   ISNULL(FIRST_NAME, ACCOUNT_MANAGER)
//   ,' '
//   ,ISNULL(LAST_NAME, '')
//   ) AS 'MANAGER_NAME'
//  ,ISNULL(IS_SYSTEM_USER, 0) AS 'IS_SYSTEM_USER'
//  ,ISNULL(USER_ACTIVE, 0) AS 'IS_ACTIVE_USER'
//  , PRODUCT_REVIEW_BY
//  ,CAST(ENABLE_PRODUCT_THRESHOLD_NOTIFICATION AS BIT) AS 'ENABLE_THRESHOLD_NOTIFICATION'
//  ,CAST(ENABLE_APROVAL AS BIT) AS 'ENABLE_APPROVAL'
//  ,ISNULL(ENABLE_PAYMENT_PROCESSING, 0) AS 'ENABLE_PAYMENT_PROCESSING'
//  ,ISNULL(ENABLE_STATEMENT_RECONCILIATION, 0) AS 'ENABLE_STATEMENT_RECONCILIATION'
//  ,ISNULL(DISABLEONDEMANDEXTRACT, 0) AS 'DISABLEONDEMANDEXTRACT'
//  ,ISNULL(ENABLE_CENTRALISED_INVOICE_PROCESSING, 0) AS 'ENABLE_CENTRALISED_INVOICE_PROCESSING'
//  , CENTRALISED_PROCESSING_LOCATION
//  ,ISNULL(ISENABLE_CENTRALISED_PROCESSING_LOCATION_ONLY, 0) AS 'ISENABLE_CENTRALISED_PROCESSING_LOCATION_ONLY'
//  ,ISNULL(CAST(PAID_DATE_MANDATORY AS BIT), 0) AS 'PAID_DATE_MANDATORY'
//  ,ISNULL(CAST(PAID_AMOUNT_MANDATORY AS BIT), 0) AS 'PAID_AMOUNT_MANDATORY'
//  ,ISNULL(CAST(PAYMENT_REFERENCE_NUMBER_MANDATORY AS BIT), 0) AS 'PAYMENT_REFERENCE_NUMBER_MANDATORY'
//  ,ISNULL(CAST(MEMO_MANDATORY AS BIT), 0) AS 'MEMO_MANDATORY'
//  , CASE
//   WHEN PAID_AMOUNT_DEFAULT = 'INVOICE AMOUNT'
//    THEN 1
//   ELSE 0
//   END AS 'PAID_AMOUNT_DEFAULT'
//  , CASE
//   WHEN PAID_DATE_DEFAULT = 'INVOICE DATE'
//    THEN 1
//   WHEN PAID_DATE_DEFAULT = 'UPLOAD DATE'
//    THEN 2
//   ELSE 0
//   END AS 'PAID_DATE_DEFAULT'
//  , CASE
//   WHEN ENABLE_DUPLICATE_PRODUCT = 1
//    THEN 1
//   ELSE 0
//   END AS 'ENABLE_DUPLICATE_PRODUCT'
//  ,CAST(DISABLE_APPROVAL_EMAIL_NOTIFICATION AS BIT) AS 'ENABLE_APPROVAL_EMAIL_NOTIFICATION'
//  ,ISNULL(CAST(ENABLE_QUICKBOOKS_LOCATIONINVOICE AS BIT), 0) AS 'ENABLE_QUICKBOOKS_LOCATIONINVOICE'
//  ,ISNULL(CAST(ENABLE_REPROCESS_INVOICE AS BIT), 0) AS 'ENABLE_REPROCESS_INVOICE'
//  ,ISNULL(CAST(ENABLE_THIRDPARTY_INTEGRATION_SERVICES AS BIT), 0) AS 'ENABLE_THIRDPARTY_INTEGRATION_SERVICES'
//  ,ISNULL(CAST(INTACCT_JOURNAL_EXTRACT AS BIT), 0) AS 'INTACCT_JOURNAL_EXTRACT'
//  ,ISNULL(CAST(INTACCT_JOURNAL_API_EXTRACT AS BIT), 0) AS 'INTACCT_JOURNAL_API_EXTRACT'
//  ,ISNULL(CAST(ENABLE_INVENTORY AS BIT), 0) AS 'ENABLE_INVENTORY'
//  ,ISNULL(CAST(DISABLE_SYSTEMREJECT AS BIT), 0) AS 'DISABLE_SYSTEMREJECT'
//  ,ISNULL(DISABLE_SYSTEMREJECT_REASON, '') AS 'DISABLE_SYSTEMREJECT_REASON'
//  ,ISNULL(CAST(ENABLE_POSTING_DATE AS BIT), 0) AS 'ENABLE_POSTING_DATE'
//  , CASE
//   WHEN POSTING_DATE_PREFERENCE = 'INVOICE_DATE'
//    THEN 1
//   WHEN POSTING_DATE_PREFERENCE = 'EXTRACT_DATE'
//    THEN 2
//   ELSE 0
//   END AS 'POSTING_DATE_PREFERENCE'
//  ,ISNULL(CAST(ENABLE_JOURNAL AS BIT), 0) AS 'ENABLE_JOURNAL'
//  , CASE
//   WHEN DISCOUNT_BY = 'SALES'
//    THEN 1
//   WHEN DISCOUNT_BY = 'DISCOUNT'
//    THEN 2
//   ELSE 0
//   END AS 'DISCOUNT_BY_PREFERENCE'
//  ,ISNULL(CAST(INV_DUP_WITHINAPPROVAL AS BIT), 0) AS 'INV_DUP_WITHINAPPROVAL'
//  , CASE
//   WHEN JOURNAL_POSTING_BY = 'Gross'
//    THEN 1
//   WHEN JOURNAL_POSTING_BY = 'Net'
//    THEN 2
//   ELSE 0
//   END AS 'JOURNAL_POSTING_BY'
//  ,ISNULL(CAST(ENABLE_RECIPE AS BIT), 0) AS 'ENABLE_RECIPE'
//  ,ISNULL(CAST(ENABLE_RMS_MASTER_CONFIG_SYNC AS BIT), 0) AS 'ENABLE_RMS_MASTER_CONFIG_SYNC'
//  ,ISNULL(CAST(ENABLE_CHANGE_VENDOR_REQUEST AS BIT), 0) AS 'ENABLE_CHANGE_VENDOR_REQUEST'
//  ,ISNULL(CAST(ENABLE_BILL_PAY AS BIT), 0) AS 'ENABLE_BILL_PAY'
//  ,ISNULL(CAST(ENABLE_VENDOR_HUB AS BIT), 0) AS 'ENABLE_VENDOR_HUB'
//  ,ISNULL(CAST(ENROLLED_FOR_XTRACASH AS BIT), 0) AS 'ENROLLED_FOR_XTRACASH'
//  ,ISNULL(CAST(REGISTERED_FOR_BUYERS_EDGE AS BIT), 0) AS 'REGISTERED_FOR_BUYERS_EDGE'
//  , CASE
//   WHEN PACKAGE_CODE = 'XC_CASH'
//    THEN 1
//   ELSE 0
//   END AS 'PACKAGE_CODE'
//  , IsSystemTenant
//  , IsNonUSTenant
//  ,CAST(ISNULL(TenantStatus, '1') AS BIT) AS 'TenantStatus'
//  , UPLOAD_TRIAL_END_ON AS 'UPLOAD_TRIAL_END_ON'
//  ,CONVERT(VARCHAR(10), CREATED_ON, 101) AS CREATED_ON
//  ,ISNULL(CAST(SYNC_ENABLE_ACCT_POSTING_FREQUENCY AS BIT), 0) AS 'SYNC_ENABLE_ACCT_POSTING_FREQUENCY'
//  ,ISNULL(CAST(ENABLE_INAPP_NOTIFICATION AS BIT), 0) AS 'ENABLE_INAPP_NOTIFICATION'
//  ,ISNULL(CAST(ENABLE_COSTCENTRE_ALLOCATION_SAVE_TEMPLATE AS BIT), 0) AS 'ENABLE_COSTCENTRE_ALLOCATION_SAVE_TEMPLATE'
//  ,ISNULL(CAST(INV_DUP_WITHINCOSTCENTER AS BIT), 0) AS 'INV_DUP_WITHINCOSTCENTER'
//  ,ISNULL(CAST(BILL_PAY_APPROVAL AS BIT), 0) AS 'BILL_PAY_APPROVAL'
//  ,ISNULL(CAST(ENABLE_DISCOUNT_BY_REVENUE_CENTER AS BIT), 0) AS 'ENABLE_DISCOUNT_BY_REVENUE_CENTER'
//  ,ISNULL(CAST(SKIP_INTERNAL_LOCATION_MAPPING AS BIT), 0) AS 'SKIP_INTERNAL_LOCATION_MAPPING'
//  ,ISNULL(CAST(QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD AS BIT), 0) AS 'QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD'
//  ,ISNULL(CAST(ENABLE_CREDIT_COST_CENTER_ALLOCATION AS BIT), 0) AS 'ENABLE_CREDIT_COST_CENTER_ALLOCATION'
//  ,ISNULL(CAST(ENABLE_CENTRAL_KITCHEN_ORDER_PROCESSING AS BIT), 0) AS 'ENABLE_CENTRAL_KITCHEN_ORDER_PROCESSING'
//  ,ISNULL(CAST(SHOW_VENDOR_CODE_IN_APPROVAL AS BIT), 0) AS 'SHOW_VENDOR_CODE_IN_APPROVAL'
//  ,ISNULL(CAST(EDIT_PRODUCT_DESCRIPTION AS BIT), 0) AS 'EDIT_PRODUCT_DESCRIPTION'
//  ,ISNULL(PRODUCT_NAME_DISPLAY_OPTIONS, @DEFAULT_PRODUCT_DESC_OPTION) AS 'PRODUCT_NAME_DISPLAY_OPTIONS'
//  ,ISNULL(CAST(ENABLE_MARKET_TRENDS AS BIT), 0) AS 'ENABLE_MARKET_TRENDS'
//  ,ISNULL(CAST(ENABLE_PRODUCT_REVIEW_FOR_EDI_INVOICE AS BIT), 0) AS 'ENABLE_PRODUCT_REVIEW_FOR_EDI_INVOICE'
//  ,ISNULL(CAST(ENABLE_PAYROLL AS BIT), 0) AS 'ENABLE_PAYROLL'
//  ,ISNULL(CAST(WEBHOOKS_QUICKBOOKS_ONLINE_ENABLE AS BIT), 0) AS 'WEBHOOKS_QUICKBOOKS_ONLINE_ENABLE'
//  ,ISNULL(CAST(WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_GL AS BIT), 0) AS 'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_GL'
//  ,ISNULL(CAST(WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_CLASSES AS BIT), 0) AS 'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_CLASSES'
//  ,ISNULL(CAST(WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_VENDORS AS BIT), 0) AS 'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_VENDORS'
//  ,ISNULL(CAST(WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_PAYMENT_TERMS AS BIT), 0) AS 'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_PAYMENT_TERMS'
//  ,ISNULL(CAST(WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_BILL_PAYMENT AS BIT), 0) AS 'WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_BILL_PAYMENT'
//  ,ISNULL(WEBHOOKS_QUICKBOOKS_ONLINE_AUDIT_DATETIME, '') AS 'WEBHOOKS_QUICKBOOKS_ONLINE_AUDIT_DATETIME'
//  ,ISNULL(WEBHOOKS_QUICKBOOKS_ONLINE_USER_ID, 0) AS 'WEBHOOKS_QUICKBOOKS_ONLINE_USER_ID'
//  ,ISNULL(CAST(POST_BILLPAY_PAYMENT_TO_ACCT_SYSTEM AS BIT), 0) AS 'POST_BILLPAY_PAYMENT_TO_ACCT_SYSTEM'
//  ,ISNULL(CAST(ENABLE_DRIFT_CHAT AS BIT), 1) AS 'ENABLE_DRIFT_CHAT'
//  , BILL_PAY_CUTOFF_DATE AS 'BILL_PAY_CUTOFF_DATE'
//  ,ISNULL(CAST(AUTO_ASSIGN_INVOICE_ID_FOR_TENANT AS BIT), 0) AS 'AUTO_ASSIGN_INVOICE_ID_FOR_TENANT'
//  ,ISNULL(CAST(ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM AS BIT), 0) AS 'ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM'
//  ,ISNULL(CAST(ENABLE_BOOKS AS BIT), 0) AS 'ENABLE_BOOKS' 
//  ,ISNULL(CAST(ENABLE_PREDICTIVE_CATEGORY_MAPPING AS BIT), 0) AS 'ENABLE_PREDICTIVE_CATEGORY_MAPPING' 
//  ,ISNULL(CAST(ENABLE_SKIP_MISSING_VENDOR_CODE_EXCEPTION AS BIT), 0) AS 'ENABLE_SKIP_MISSING_VENDOR_CODE_EXCEPTION'
//  ,ISNULL(CAST(QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE AS BIT), 0) AS 'QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE'
//  ,ISNULL(CAST(QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE AS BIT), 0) AS 'QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE'
//  ,ISNULL(CAST(WHITE_GLOVE_CUSTOMER AS BIT), 0) AS 'WHITE_GLOVE_CUSTOMER'
//  ,ISNULL(CAST(AUTOCORRECT_PREVIOUS_PURCHASE AS BIT), 1) AS 'AUTOCORRECT_PREVIOUS_PURCHASE'

// FROM (
//  SELECT DISTINCT XT.*
//   ,XTC.CONFIG_VALUE
//   ,CKT.ConfigKey
//   ,XUT.FIRST_NAME
//   ,XUT.LAST_NAME
//   ,XUT.IS_SYSTEM_USER
//   ,XUT.ACTIVE AS 'USER_ACTIVE'
//  FROM [dbo].[XC_TENANT] XT WITH(NOLOCK)
//  LEFT JOIN[dbo].[XC_USER] XUT WITH(NOLOCK) ON XT.ACCOUNT_MANAGER = XUT.[USER_NAME]
//  AND XT.TENANT_ID = XUT.TENANT_ID
//  INNER JOIN[dbo].[XC_TENANT_CONFIG] XTC WITH(NOLOCK) ON XT.TENANT_ID = XTC.TENANT_ID
//  INNER JOIN #CONFIGKEYTABLE CKT WITH (NOLOCK) ON CKT.ConfigKey = XTC.CONFIG_KEY
//  WHERE XT.TENANT_ID = @TENANT_ID_IP
//  ) AS SourceTable
// PIVOT(max(CONFIG_VALUE) FOR ConfigKey IN (
//    [ENABLE_PRODUCT_CATALOG_BETA]
//    ,[COMPEAT_EXTRACT]
//    ,[IMAGE_EXTRACT]
//    ,[QUICKBOOK_EXTRACT]
//    ,[R365_EXTRACT]
//    ,[ENABLE_PRODUCT_THRESHOLD_NOTIFICATION]
//    ,[ENABLE_APROVAL]
//    ,[PAID_DATE_MANDATORY]
//    ,[PAID_AMOUNT_MANDATORY]
//    ,[PAYMENT_REFERENCE_NUMBER_MANDATORY]
//    ,[MEMO_MANDATORY]
//    ,[PAID_AMOUNT_DEFAULT]
//    ,[PAID_DATE_DEFAULT]
//    ,[ENABLE_DUPLICATE_PRODUCT]
//    ,[DISABLE_APPROVAL_EMAIL_NOTIFICATION]
//    ,[ENABLE_QUICKBOOKS_LOCATIONINVOICE]
//    ,[ENABLE_REPROCESS_INVOICE]
//    ,[ENABLE_THIRDPARTY_INTEGRATION_SERVICES]
//    ,[INTACCT_JOURNAL_EXTRACT]
//    ,[INTACCT_JOURNAL_API_EXTRACT]
//    ,[ENABLE_INVENTORY]
//    ,[DISABLE_SYSTEMREJECT]
//    ,[DISABLE_SYSTEMREJECT_REASON]
//    ,[ENABLE_POSTING_DATE]
//    ,[POSTING_DATE_PREFERENCE]
//    ,[ENABLE_JOURNAL]
//    ,[DISCOUNT_BY]
//    ,[INV_DUP_WITHINAPPROVAL]
//    ,[JOURNAL_POSTING_BY]
//    ,[ENABLE_RECIPE]
//    ,[ENABLE_RMS_MASTER_CONFIG_SYNC]
//    ,[ENABLE_CHANGE_VENDOR_REQUEST]
//    ,[ENABLE_BILL_PAY]
//    ,[ENABLE_VENDOR_HUB]
//    ,[ENROLLED_FOR_XTRACASH]
//    ,[REGISTERED_FOR_BUYERS_EDGE]
//    ,[PACKAGE_CODE]
//    ,[UPLOAD_TRIAL_END_ON]
//    ,[SYNC_ENABLE_ACCT_POSTING_FREQUENCY]
//    ,[ENABLE_INAPP_NOTIFICATION]
//	,[ENABLE_COSTCENTRE_ALLOCATION_SAVE_TEMPLATE]
//    ,[INV_DUP_WITHINCOSTCENTER]
//    ,[BILL_PAY_APPROVAL]
//    ,[ENABLE_DISCOUNT_BY_REVENUE_CENTER]
//    ,[SKIP_INTERNAL_LOCATION_MAPPING]
//    ,[QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD]
//    ,[ENABLE_CREDIT_COST_CENTER_ALLOCATION]
//    ,[ENABLE_CENTRAL_KITCHEN_ORDER_PROCESSING]
//    ,[SHOW_VENDOR_CODE_IN_APPROVAL]
//    ,[EDIT_PRODUCT_DESCRIPTION]
//    ,[PRODUCT_NAME_DISPLAY_OPTIONS]
//    ,[ENABLE_MARKET_TRENDS]
//    ,[ENABLE_PRODUCT_REVIEW_FOR_EDI_INVOICE]
//    ,[ENABLE_PAYROLL]
//    ,[WEBHOOKS_QUICKBOOKS_ONLINE_ENABLE]
//    ,[WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_GL]
//    ,[WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_CLASSES]
//    ,[WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_VENDORS]
//    ,[WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_PAYMENT_TERMS]
//    ,[WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_BILL_PAYMENT]
//    ,[WEBHOOKS_QUICKBOOKS_ONLINE_AUDIT_DATETIME]
//    ,[WEBHOOKS_QUICKBOOKS_ONLINE_USER_ID]
//    ,[POST_BILLPAY_PAYMENT_TO_ACCT_SYSTEM]
//    ,[ENABLE_DRIFT_CHAT]
//    ,[BILL_PAY_CUTOFF_DATE]
//	,[AUTO_ASSIGN_INVOICE_ID_FOR_TENANT]
//	,[ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM]
//    ,[ENABLE_BOOKS] 
//	,[ENABLE_PREDICTIVE_CATEGORY_MAPPING]
//	,[ENABLE_SKIP_MISSING_VENDOR_CODE_EXCEPTION]
//	,[QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE]
//	,[QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE]
//	,[WHITE_GLOVE_CUSTOMER]
//	,[AUTOCORRECT_PREVIOUS_PURCHASE]
//    )) AS PT

// DROP TABLE IF EXISTS #CONFIGKEYTABLE

// SET NOCOUNT OFF
//END
//GO

//    CREATE PROCEDURE [dbo].[XC_UPDATE_TENANT_TESTED]
//(
// @TENANT_ID BIGINT
// , @TENANT_NAME NVARCHAR(100)
// , @ACTIVE BIT
// , @ENABLE_PRODUCT_CATALOG_BETA BIT
// , @CUSTOMCATEGORY BIT
// , @APPTYPE BIGINT
// , @STARTDAY VARCHAR(50)
//, @EXTRACT BIT
// , @ENABLE_CREDITENTRY BIT
// , @EXTRACTIMAGES BIT
// , @GROUP_ID BIGINT
// , @ENABLE_COST_CENTRE BIT
// , @PRODUCT_REVIEW_BY BIGINT
// , @ENABLE_PRODUCT_THRESHOLD_NOTIFICATION BIT
// , @ENABLE_APPROVAL BIT
// , @ENABLEPAYMENTPROCESSING BIT
// , @PAIDDATEMANDATORY BIT
// , @PAIDDATEDEFAULT INT
// , @PAIDAMOUNTMANDATORY BIT
// , @PAIDAMOUNTDEFAULT INT
// , @PAYMENTREFERENCENUMBERMANDATORY BIT
// , @MEMOMANDATORY BIT
// , @ENABLE_PRODUCT_DUPLICATE_VERIFICATION BIT
// , @DISABLE_APPROVAL_EMAIL_NOTIFICATION BIT
// , @ENABLE_QUICKBOOKS_LOCATIONINVOICE BIT
// , @ENABLE_STATEMENT_RECONCILIATION BIT = NULL
//, @ENABLE_REPROCESS_INVOICE BIT
// , @DISABLEONDEMANDEXTRACT BIT
// , @ENABLE_CENTRALISED_INVOICE_PROCESSING BIT
// , @CENTRALISED_PROCESSING_LOCATION BIGINT
// , @ISENABLE_CENTRALISED_PROCESSING_LOCATION_ONLY BIT
// , @ENABLE_THIRDPARTY_INTEGRATION_SERVICES BIT
// , @INTACCT_JOURNAL_EXTRACT BIT
// , @INTACCT_JOURNAL_API_EXTRACT BIT
// , @ENABLE_INVENTORY BIT
// , @DISABLEAUTOREJECT BIT
// , @DISABLEAUTOREJECTREASONS VARCHAR(100)
// , @ENABLE_RECIPE BIT
// , @ENABLE_POSTING_DATE BIT
// , @POSTINGDATEPREFERENCE INT
// , @ENABLEJOURNALPOSTING BIT
// , @JOURNALPOSTINGBY INT
// , @ENABLE_RMS_MASTER_CONFIG_SYNC BIT
// , @ENABLE_CHANGE_VENDOR_REQUEST BIT
// , @ENABLE_BILL_PAY BIT
// , @ENABLEINVDUPWITHINAPPROVAL BIT
// , @ENABLEVENDORHUB BIT
// , @DISCOUNTBY INT
// , @XTRACHEFACCOUNTMANAGERID VARCHAR(50)
// , @SYSTEMTENANT BIT
// , @NONUSTENANT BIT
// , @SYNC_EXPIRES_ON VARCHAR(11)
// , @IS_LOCATION_CONFIG_TO_BE_CHANGED BIT = 0
// , @ENABLE_ACCOUNTING_FREQUENCY BIT
// , @ENABLE_INAPP_NOTIFICATION BIT
// , @ENABLE_COSTCENTRE_SAVE_TEMPLATE BIT
// , @ENABLEINVDUPWITHINCOSTCENTER BIT = 0
// , @ENABLEBILLPAYAPPROVAL BIT
// , @ENABLEDISCOUNTBYREVENUECENTER BIT
// , @SKIP_INTERNAL_LOCATION_MAPPING BIT
// , @QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD BIT
// , @ENABLECREDITCOSTCENTERALLOCATION BIT
// , @USER_ID BIGINT
// , @ENABLECENTRALKITCHENORDERPROCESSING BIT
// , @BROWSER VARCHAR(50)
// , @VERSION VARCHAR(50)
// , @SHOWVENDORCODEINAPPROVAL BIT
// , @ENABLEEDITPRODUCTDESCRIPTION BIT
// , @PRODUCTNAMEDISPLAYOPTION VARCHAR(50)
// , @ENABLEMARKETTRENDS BIT
// , @ENABLEPRODUCTREVIREFOREDIINVOICE BIT
// , @ENABLEPAYROLLSETUP BIT
// , @ENABLEWEBHOOKSQUICKBOOKSONLINEENABLE BIT
// , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCGL BIT
// , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCCLASSES BIT
// , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCVENDORS BIT
// , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCPAYMENTTERMS BIT
// , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCBILLPAYMENT BIT
// , @WEBHOOKSQUICKBOOKSONLINEAUDITDATETIME VARCHAR(500)
// , @WEBHOOKSQUICKBOOKSONLINEUSERID BIGINT
// , @POSTBILLPAYPAYMENTTOACCTSYSTEM BIT
// , @ENABLEDRIFTCHAT BIT
// , @BILLPAYCUTOFFDATE VARCHAR(11)
// , @ENABLEAUTOASSIGNINVOICEID BIT
// , @ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM BIT
// , @ENABLEBOOKS BIT
// , @ENABLEWHITEGLOVECUSTOMER BIT
// , @DISABLE_QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE BIT
// , @DISABLE_QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE BIT
// , @ENABLE_AUTOCORRECT_PREVIOUS_PURCHASE BIT
// )
//AS
//BEGIN	
// DECLARE @GETDATE DATETIME = GETDATE()
//  , @PRODUCT_ID VARCHAR(MAX)
//  , @PRODUCT_COUNT BIGINT
//  , @ErrorMessage NVARCHAR(4000)
//  , @ErrorSeverity INT
//  , @ErrorState INT
//  , @IS_PRODUCT_REVIEW_PREVIOUS BIGINT
//  , @TENANT_ID_IP BIGINT
//  , @TENANT_NAME_IP NVARCHAR(100)
//  , @ACTIVE_IP BIT
//  , @ENABLE_PRODUCT_CATALOG_BETA_IP BIT
//  , @CUSTOMCATEGORY_IP BIT
//  , @APPTYPE_IP BIGINT
//  , @STARTDAY_IP VARCHAR(50)
//  , @EXTRACT_IP BIT
//  , @ENABLE_CREDITENTRY_IP BIT
//  , @EXTRACTIMAGES_IP BIT
//  , @GROUP_ID_IP BIGINT
//  , @ENABLE_COST_CENTRE_IP BIT
//  , @PRODUCT_REVIEW_BY_IP BIGINT
//  , @ENABLE_PRODUCT_THRESHOLD_NOTIFICATION_IP BIT
//  , @ENABLE_APPROVAL_IP BIT
//  , @ENABLEPAYMENTPROCESSING_IP BIT
//  , @PAIDDATEMANDATORY_IP BIT
//  , @PAIDDATEDEFAULT_IP INT
//  , @PAIDAMOUNTMANDATORY_IP BIT
//  , @PAIDAMOUNTDEFAULT_IP INT
//  , @PAYMENTREFERENCENUMBERMANDATORY_IP BIT
//  , @MEMOMANDATORY_IP BIT
//  , @ENABLE_PRODUCT_DUPLICATE_VERIFICATION_IP BIT
//  , @DISABLE_APPROVAL_EMAIL_NOTIFICATION_IP BIT
//  , @ENABLE_QUICKBOOKS_LOCATIONINVOICE_IP BIT
//  , @ENABLE_STATEMENT_RECONCILIATION_IP BIT = NULL
//  , @ENABLE_REPROCESS_INVOICE_IP BIT
//  , @DISABLEONDEMANDEXTRACT_IP BIT    , @ENABLE_CENTRALISED_INVOICE_PROCESSING_IP BIT
//  , @CENTRALISED_PROCESSING_LOCATION_IP BIGINT
//  , @ISENABLE_CENTRALISED_PROCESSING_LOCATION_ONLY_IP BIT
//  , @ENABLE_THIRDPARTY_INTEGRATION_SERVICES_IP BIT
//  , @INTACCT_JOURNAL_EXTRACT_IP BIT
//  , @INTACCT_JOURNAL_API_EXTRACT_IP BIT
//  , @ENABLE_INVENTORY_IP BIT
//  , @DISABLEAUTOREJECT_IP BIT
//  , @DISABLEAUTOREJECTREASONS_IP VARCHAR(100)
//  , @ENABLE_RECIPE_IP BIT
//  , @ENABLE_POSTING_DATE_IP BIT
//  , @POSTINGDATEPREFERENCE_IP INT
//  , @ENABLEJOURNALPOSTING_IP BIT
//  , @JOURNALPOSTINGBY_IP INT
//  , @ENABLE_RMS_MASTER_CONFIG_SYNC_IP BIT
//  , @ENABLE_CHANGE_VENDOR_REQUEST_IP BIT
//  , @ENABLE_BILL_PAY_IP BIT
//  , @ENABLEINVDUPWITHINAPPROVAL_IP BIT
//  , @ENABLEVENDORHUB_IP BIT
//  , @DISCOUNTBY_IP INT
//  , @XTRACHEFACCOUNTMANAGERID_IP VARCHAR(50)
//  , @SYSTEMTENANT_IP BIT
//  , @NONUSTENANT_IP BIT
//  , @SYNC_EXPIRES_ON_IP VARCHAR(11)
//  , @IS_LOCATION_CONFIG_TO_BE_CHANGED_IP BIT = 0
//  , @ENABLE_ACCOUNTING_FREQUENCY_IP BIT
//  , @ENABLE_INAPP_NOTIFICATION_IP BIT
//  , @ENABLE_COSTCENTRE_SAVE_TEMPLATE_IP BIT
//  , @ENABLEINVDUPWITHINCOSTCENTER_IP BIT = 0
//  , @ENABLEBILLPAYAPPROVAL_IP BIT
//  , @ENABLEDISCOUNTBYREVENUECENTER_IP BIT
//  , @SKIP_INTERNAL_LOCATION_MAPPING_IP BIT
//  , @QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD_IP BIT
//  , @ENABLECREDITCOSTCENTERALLOCATION_IP BIT
//  , @USER_ID_IP BIGINT
//  , @ENABLECENTRALKITCHENORDERPROCESSING_IP BIT
//  , @BROWSER_IP VARCHAR(50)
//  , @VERSION_IP VARCHAR(50)
//  , @SHOWVENDORCODEINAPPROVAL_IP BIT
//  , @ENABLEEDITPRODUCTDESCRIPTION_IP BIT
//  , @PRODUCTNAMEDISPLAYOPTION_IP VARCHAR(50)
//  , @ENABLEMARKETTRENDS_IP BIT
//  , @ENABLEPRODUCTREVIREFOREDIINVOICE_IP BIT
//  , @ENABLEPAYROLLSETUP_IP BIT
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINEENABLE_IP BIT
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCGL_IP BIT
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCCLASSES_IP BIT
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCVENDORS_IP BIT
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCPAYMENTTERMS_IP BIT
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCBILLPAYMENT_IP BIT
//  , @WEBHOOKSQUICKBOOKSONLINEUSERID_IP VARCHAR(20)
//  , @WEBHOOKSQUICKBOOKSONLINEAUDITDATETIME_IP VARCHAR(500)
//  , @POSTBILLPAYPAYMENTTOACCTSYSTEM_IP BIT
//  , @ENABLEDRIFTCHAT_IP BIT
//  , @BILLPAYCUTOFFDATE_IP VARCHAR(11)
//  , @ENABLEAUTOASSIGNINVOICEID_IP BIT
//  , @ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM_IP BIT
//  , @ENABLEBOOKS_IP BIT 
//  , @DISABLE_QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE_IP BIT
//  , @DISABLE_QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE_IP BIT
//  , @ENABLEWHITEGLOVECUSTOMER_IP BIT
//  , @ENABLE_AUTOCORRECT_PREVIOUS_PURCHASE_IP BIT

// SELECT @TENANT_ID_IP = @TENANT_ID
//  , @TENANT_NAME_IP = @TENANT_NAME
//  , @ACTIVE_IP = @ACTIVE
//  , @ENABLE_PRODUCT_CATALOG_BETA_IP = @ENABLE_PRODUCT_CATALOG_BETA
//  , @CUSTOMCATEGORY_IP = @CUSTOMCATEGORY
//  , @APPTYPE_IP = @APPTYPE
//  , @STARTDAY_IP = @STARTDAY
//  , @EXTRACT_IP = @EXTRACT
//  , @ENABLE_CREDITENTRY_IP = @ENABLE_CREDITENTRY
//  , @EXTRACTIMAGES_IP = @EXTRACTIMAGES
//  , @GROUP_ID_IP = @GROUP_ID
//  , @ENABLE_COST_CENTRE_IP = @ENABLE_COST_CENTRE
//  , @PRODUCT_REVIEW_BY_IP = @PRODUCT_REVIEW_BY
//  , @ENABLE_PRODUCT_THRESHOLD_NOTIFICATION_IP = @ENABLE_PRODUCT_THRESHOLD_NOTIFICATION
//  , @ENABLE_APPROVAL_IP = @ENABLE_APPROVAL
//  , @ENABLEPAYMENTPROCESSING_IP = @ENABLEPAYMENTPROCESSING
//  , @PAIDDATEMANDATORY_IP = @PAIDDATEMANDATORY
//  , @PAIDDATEDEFAULT_IP = @PAIDDATEDEFAULT
//  , @PAIDAMOUNTMANDATORY_IP = @PAIDAMOUNTMANDATORY
//  , @PAIDAMOUNTDEFAULT_IP = @PAIDAMOUNTDEFAULT
//  , @PAYMENTREFERENCENUMBERMANDATORY_IP = @PAYMENTREFERENCENUMBERMANDATORY
//  , @MEMOMANDATORY_IP = @MEMOMANDATORY
//  , @ENABLE_PRODUCT_DUPLICATE_VERIFICATION_IP = @ENABLE_PRODUCT_DUPLICATE_VERIFICATION
//  , @DISABLE_APPROVAL_EMAIL_NOTIFICATION_IP = @DISABLE_APPROVAL_EMAIL_NOTIFICATION
//  , @ENABLE_QUICKBOOKS_LOCATIONINVOICE_IP = @ENABLE_QUICKBOOKS_LOCATIONINVOICE
//  , @ENABLE_STATEMENT_RECONCILIATION_IP = @ENABLE_STATEMENT_RECONCILIATION
//  , @ENABLE_REPROCESS_INVOICE_IP = @ENABLE_REPROCESS_INVOICE
//  , @DISABLEONDEMANDEXTRACT_IP = @DISABLEONDEMANDEXTRACT
//  , @ENABLE_CENTRALISED_INVOICE_PROCESSING_IP = @ENABLE_CENTRALISED_INVOICE_PROCESSING
//  , @CENTRALISED_PROCESSING_LOCATION_IP = @CENTRALISED_PROCESSING_LOCATION
//  , @ISENABLE_CENTRALISED_PROCESSING_LOCATION_ONLY_IP = @ISENABLE_CENTRALISED_PROCESSING_LOCATION_ONLY
//  , @ENABLE_THIRDPARTY_INTEGRATION_SERVICES_IP = @ENABLE_THIRDPARTY_INTEGRATION_SERVICES
//  , @INTACCT_JOURNAL_EXTRACT_IP = @INTACCT_JOURNAL_EXTRACT
//  , @INTACCT_JOURNAL_API_EXTRACT_IP = @INTACCT_JOURNAL_API_EXTRACT
//  , @ENABLE_INVENTORY_IP = @ENABLE_INVENTORY
//  , @DISABLEAUTOREJECT_IP = @DISABLEAUTOREJECT
//  , @DISABLEAUTOREJECTREASONS_IP = @DISABLEAUTOREJECTREASONS
//  , @ENABLE_RECIPE_IP = @ENABLE_RECIPE
//  , @ENABLE_POSTING_DATE_IP = @ENABLE_POSTING_DATE
//  , @POSTINGDATEPREFERENCE_IP = @POSTINGDATEPREFERENCE
//  , @ENABLEJOURNALPOSTING_IP = @ENABLEJOURNALPOSTING
//  , @JOURNALPOSTINGBY_IP = @JOURNALPOSTINGBY
//  , @ENABLE_RMS_MASTER_CONFIG_SYNC_IP = @ENABLE_RMS_MASTER_CONFIG_SYNC
//  , @ENABLE_CHANGE_VENDOR_REQUEST_IP = @ENABLE_CHANGE_VENDOR_REQUEST
//  , @ENABLE_BILL_PAY_IP = @ENABLE_BILL_PAY
//  , @ENABLEINVDUPWITHINAPPROVAL_IP = @ENABLEINVDUPWITHINAPPROVAL
//  , @ENABLEVENDORHUB_IP = @ENABLEVENDORHUB
//  , @DISCOUNTBY_IP = @DISCOUNTBY
//  , @XTRACHEFACCOUNTMANAGERID_IP = @XTRACHEFACCOUNTMANAGERID
//  , @SYSTEMTENANT_IP = @SYSTEMTENANT
//  , @NONUSTENANT_IP = @NONUSTENANT
//  , @SYNC_EXPIRES_ON_IP = @SYNC_EXPIRES_ON
//  , @IS_LOCATION_CONFIG_TO_BE_CHANGED_IP = @IS_LOCATION_CONFIG_TO_BE_CHANGED
//  , @ENABLE_ACCOUNTING_FREQUENCY_IP = @ENABLE_ACCOUNTING_FREQUENCY
//  , @ENABLE_INAPP_NOTIFICATION_IP = @ENABLE_INAPP_NOTIFICATION
//  , @ENABLE_COSTCENTRE_SAVE_TEMPLATE_IP = @ENABLE_COSTCENTRE_SAVE_TEMPLATE
//  , @ENABLEINVDUPWITHINCOSTCENTER_IP = @ENABLEINVDUPWITHINCOSTCENTER
//  , @ENABLEBILLPAYAPPROVAL_IP = @ENABLEBILLPAYAPPROVAL
//  , @ENABLEDISCOUNTBYREVENUECENTER_IP = @ENABLEDISCOUNTBYREVENUECENTER
//  , @SKIP_INTERNAL_LOCATION_MAPPING_IP = @SKIP_INTERNAL_LOCATION_MAPPING
//  , @QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD_IP = @QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD
//  , @ENABLECREDITCOSTCENTERALLOCATION_IP = @ENABLECREDITCOSTCENTERALLOCATION
//  , @USER_ID_IP = @USER_ID
//  , @ENABLECENTRALKITCHENORDERPROCESSING_IP = @ENABLECENTRALKITCHENORDERPROCESSING
//  , @BROWSER_IP = @BROWSER
//  , @VERSION_IP = @VERSION
//  , @SHOWVENDORCODEINAPPROVAL_IP = @SHOWVENDORCODEINAPPROVAL
//  , @ENABLEEDITPRODUCTDESCRIPTION_IP = @ENABLEEDITPRODUCTDESCRIPTION
//  , @PRODUCTNAMEDISPLAYOPTION_IP = @PRODUCTNAMEDISPLAYOPTION
//  , @ENABLEMARKETTRENDS_IP = @ENABLEMARKETTRENDS
//  , @ENABLEPRODUCTREVIREFOREDIINVOICE_IP = @ENABLEPRODUCTREVIREFOREDIINVOICE
//  , @ENABLEPAYROLLSETUP_IP = @ENABLEPAYROLLSETUP
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINEENABLE_IP = @ENABLEWEBHOOKSQUICKBOOKSONLINEENABLE
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCGL_IP = @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCGL
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCCLASSES_IP = @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCCLASSES
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCVENDORS_IP = @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCVENDORS
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCPAYMENTTERMS_IP = @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCPAYMENTTERMS
//  , @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCBILLPAYMENT_IP = @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCBILLPAYMENT
//  , @WEBHOOKSQUICKBOOKSONLINEAUDITDATETIME_IP = CAST(@WEBHOOKSQUICKBOOKSONLINEAUDITDATETIME AS VARCHAR)
//  , @WEBHOOKSQUICKBOOKSONLINEUSERID_IP = CAST(@WEBHOOKSQUICKBOOKSONLINEUSERID AS VARCHAR)
//  , @POSTBILLPAYPAYMENTTOACCTSYSTEM_IP = @POSTBILLPAYPAYMENTTOACCTSYSTEM
//  , @ENABLEDRIFTCHAT_IP = @ENABLEDRIFTCHAT
//  , @BILLPAYCUTOFFDATE_IP = @BILLPAYCUTOFFDATE
//  , @ENABLEAUTOASSIGNINVOICEID_IP = @ENABLEAUTOASSIGNINVOICEID
//  , @ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM_IP = @ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM
//  , @ENABLEBOOKS_IP = @ENABLEBOOKS
//  , @ENABLEWHITEGLOVECUSTOMER_IP = @ENABLEWHITEGLOVECUSTOMER
//  , @ENABLE_AUTOCORRECT_PREVIOUS_PURCHASE_IP = @ENABLE_AUTOCORRECT_PREVIOUS_PURCHASE
//  , @DISABLE_QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE_IP = @DISABLE_QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE
//  , @DISABLE_QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE_IP = @DISABLE_QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE


//  SELECT 
//	@IS_PRODUCT_REVIEW_PREVIOUS = PRODUCT_REVIEW_BY
//  FROM [DBO].[XC_TENANT] WITH(NOLOCK)
//  WHERE TENANT_ID = @TENANT_ID_IP

//    DROP TABLE IF EXISTS #CONFIGKEYTABLE
//	DROP TABLE IF EXISTS #GLID
//	DROP TABLE IF EXISTS #VENDORID
//	DROP TABLE IF EXISTS #CLASSID
//	DROP TABLE IF EXISTS #CUSID
//	DROP TABLE IF EXISTS #PMID
//	DROP TABLE IF EXISTS #PTMID
//	DROP TABLE IF EXISTS #TCTEMP

// CREATE TABLE #CONFIGKEYTABLE (
//   CONFIG_KEY NVARCHAR(255)
//   , CONFIG_VALUE VARCHAR(max)
//   )

// IF NOT EXISTS (
//   SELECT 1
//   FROM [DBO].[XC_TENANT_CONFIG] WITH(NOLOCK)
//   WHERE CONFIG_KEY = 'ENABLE_PRODUCT_CATALOG_BETA'
//   AND TENANT_ID = @TENANT_ID_IP
//   )
// BEGIN
//  SET @ENABLE_PRODUCT_CATALOG_BETA_IP = 1
// END

// IF NOT EXISTS (
//   SELECT 1
//   FROM [DBO].[XC_TENANT_CONFIG] WITH(NOLOCK)
//   WHERE CONFIG_KEY = 'ENABLE_VENDOR_HUB'
//    AND TENANT_ID = @TENANT_ID_IP
//   )
// BEGIN
//  SET @ENABLEVENDORHUB_IP = 1
// END

// INSERT INTO #CONFIGKEYTABLE
// VALUES
// ('ENABLE_PRODUCT_CATALOG_BETA',(SELECT CASE WHEN @ENABLE_PRODUCT_CATALOG_BETA_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_DUPLICATE_PRODUCT', CAST(@ENABLE_PRODUCT_DUPLICATE_VERIFICATION_IP AS VARCHAR)),
//    ('ENABLE_PRODUCT_THRESHOLD_NOTIFICATION', CAST(@ENABLE_PRODUCT_THRESHOLD_NOTIFICATION_IP AS VARCHAR)),
//    ('ENABLE_APROVAL', CAST(@ENABLE_APPROVAL_IP AS VARCHAR)),
//    ('PAID_DATE_MANDATORY', CAST(@PAIDDATEMANDATORY_IP AS VARCHAR)),
//    ('PAID_DATE_DEFAULT', (SELECT CASE WHEN @PAIDDATEDEFAULT_IP = 1 THEN 'INVOICE DATE' WHEN @PAIDDATEDEFAULT_IP = 2 THEN 'UPLOAD DATE' ELSE '0' END)),
//    ('PAID_AMOUNT_MANDATORY', CAST(@PAIDAMOUNTMANDATORY_IP AS VARCHAR)),
//    ('PAID_AMOUNT_DEFAULT', (SELECT CASE WHEN(@PAIDAMOUNTDEFAULT_IP = 1) THEN 'INVOICE AMOUNT' ELSE '0' END)),
//    ('PAYMENT_REFERENCE_NUMBER_MANDATORY', CAST(@PAYMENTREFERENCENUMBERMANDATORY AS VARCHAR)),
//    ('MEMO_MANDATORY', CAST(@MEMOMANDATORY AS VARCHAR)),
//    ('DISABLE_APPROVAL_EMAIL_NOTIFICATION', CAST(@DISABLE_APPROVAL_EMAIL_NOTIFICATION_IP AS VARCHAR)),
//    ('ENABLE_QUICKBOOKS_LOCATIONINVOICE', (SELECT CASE WHEN(@ENABLE_QUICKBOOKS_LOCATIONINVOICE_IP = 1) THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_REPROCESS_INVOICE', CAST(@ENABLE_REPROCESS_INVOICE_IP AS VARCHAR)),
//    ('ENABLE_THIRDPARTY_INTEGRATION_SERVICES', CAST(@ENABLE_THIRDPARTY_INTEGRATION_SERVICES_IP AS VARCHAR)),
//    ('INTACCT_JOURNAL_EXTRACT', (SELECT CASE WHEN @INTACCT_JOURNAL_EXTRACT_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('INTACCT_JOURNAL_API_EXTRACT', (SELECT CASE WHEN @INTACCT_JOURNAL_API_EXTRACT_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_INVENTORY', (SELECT CASE WHEN @ENABLE_INVENTORY_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('DISABLE_SYSTEMREJECT', (SELECT CASE WHEN @DISABLEAUTOREJECT_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('DISABLE_SYSTEMREJECT_REASON', @DISABLEAUTOREJECTREASONS_IP),
//    ('ENABLE_RECIPE', (SELECT CASE WHEN @ENABLE_RECIPE_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_POSTING_DATE', (SELECT CASE WHEN @ENABLE_POSTING_DATE_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_JOURNAL', (SELECT CASE WHEN @ENABLEJOURNALPOSTING_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('POSTING_DATE_PREFERENCE', (SELECT CASE WHEN @POSTINGDATEPREFERENCE_IP = 1 THEN 'INVOICE_DATE' WHEN @POSTINGDATEPREFERENCE_IP = 2 THEN 'EXTRACT_DATE' ELSE '0' END)),
//    ('JOURNAL_POSTING_BY', (SELECT CASE WHEN @JOURNALPOSTINGBY_IP = 1 THEN 'Gross' WHEN @JOURNALPOSTINGBY_IP = 2 THEN 'Net' ELSE '' END)),
//    ('ENABLE_RMS_MASTER_CONFIG_SYNC', CAST(@ENABLE_RMS_MASTER_CONFIG_SYNC_IP AS VARCHAR)),
//    ('ENABLE_CHANGE_VENDOR_REQUEST', (SELECT CASE WHEN @ENABLE_CHANGE_VENDOR_REQUEST_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_BILL_PAY', (SELECT CASE WHEN @ENABLE_BILL_PAY_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//	('ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM', (SELECT CASE WHEN @ENABLE_INVOICE_EXPORT_TO_DATA_PLATFORM_IP = 1  THEN 'TRUE' ELSE 'FALSE' END)),
//    ('INV_DUP_WITHINAPPROVAL', (SELECT CASE WHEN @ENABLEINVDUPWITHINAPPROVAL_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_VENDOR_HUB', (SELECT CASE WHEN @ENABLEVENDORHUB_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('UPLOAD_TRIAL_END_ON', (SELECT CASE WHEN @SYNC_EXPIRES_ON_IP = '' THEN NULL ELSE @SYNC_EXPIRES_ON_IP END)),
//    ('SYNC_ENABLE_ACCT_POSTING_FREQUENCY', (SELECT CASE WHEN @ENABLE_ACCOUNTING_FREQUENCY_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_INAPP_NOTIFICATION', (SELECT CASE WHEN @ENABLE_INAPP_NOTIFICATION_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_COSTCENTRE_ALLOCATION_SAVE_TEMPLATE', (SELECT CASE WHEN @ENABLE_COSTCENTRE_SAVE_TEMPLATE_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD', (SELECT CASE WHEN @QB_ENABLE_CHART_OF_ACCOUNTS_DOWNLOAD_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('INV_DUP_WITHINCOSTCENTER', (SELECT CASE WHEN @ENABLEINVDUPWITHINCOSTCENTER_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('BILL_PAY_APPROVAL', (SELECT CASE WHEN @ENABLEBILLPAYAPPROVAL_IP = 1 AND @ENABLE_BILL_PAY_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_DISCOUNT_BY_REVENUE_CENTER', (SELECT CASE WHEN @ENABLEDISCOUNTBYREVENUECENTER_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('SKIP_INTERNAL_LOCATION_MAPPING', (SELECT CASE WHEN @SKIP_INTERNAL_LOCATION_MAPPING_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_CREDIT_COST_CENTER_ALLOCATION', (SELECT CASE WHEN @ENABLECREDITCOSTCENTERALLOCATION_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_CENTRAL_KITCHEN_ORDER_PROCESSING', (SELECT CASE WHEN @ENABLECENTRALKITCHENORDERPROCESSING_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('SHOW_VENDOR_CODE_IN_APPROVAL', (SELECT CASE WHEN @SHOWVENDORCODEINAPPROVAL_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('EDIT_PRODUCT_DESCRIPTION', (SELECT CASE WHEN @ENABLEEDITPRODUCTDESCRIPTION_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('PRODUCT_NAME_DISPLAY_OPTIONS', @PRODUCTNAMEDISPLAYOPTION_IP),
//    ('ENABLE_MARKET_TRENDS', (SELECT CASE WHEN @ENABLEMARKETTRENDS_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_PRODUCT_REVIEW_FOR_EDI_INVOICE', (SELECT CASE WHEN @ENABLEPRODUCTREVIREFOREDIINVOICE_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
//    ('ENABLE_PAYROLL', (SELECT CASE WHEN @ENABLEPAYROLLSETUP_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('WEBHOOKS_QUICKBOOKS_ONLINE_ENABLE', (SELECT CASE WHEN @ENABLEWEBHOOKSQUICKBOOKSONLINEENABLE_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_GL', (SELECT CASE WHEN @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCGL_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_CLASSES', (SELECT CASE WHEN @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCCLASSES_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_VENDORS', (SELECT CASE WHEN @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCVENDORS_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_PAYMENT_TERMS', (SELECT CASE WHEN @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCPAYMENTTERMS_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('WEBHOOKS_QUICKBOOKS_ONLINE_SYNC_BILL_PAYMENT', (SELECT CASE WHEN @ENABLEWEBHOOKSQUICKBOOKSONLINESYNCBILLPAYMENT_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('WEBHOOKS_QUICKBOOKS_ONLINE_AUDIT_DATETIME', @WEBHOOKSQUICKBOOKSONLINEAUDITDATETIME_IP),
// ('WEBHOOKS_QUICKBOOKS_ONLINE_USER_ID', @WEBHOOKSQUICKBOOKSONLINEUSERID_IP),
// ('POST_BILLPAY_PAYMENT_TO_ACCT_SYSTEM', (SELECT CASE WHEN @POSTBILLPAYPAYMENTTOACCTSYSTEM_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('ENABLE_DRIFT_CHAT', (SELECT CASE WHEN @ENABLEDRIFTCHAT_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)) ,
// ('BILL_PAY_CUTOFF_DATE', (SELECT CASE WHEN @BILLPAYCUTOFFDATE_IP = '' THEN NULL ELSE @BILLPAYCUTOFFDATE_IP END)),
// ('AUTO_ASSIGN_INVOICE_ID_FOR_TENANT', (SELECT CASE WHEN @ENABLEAUTOASSIGNINVOICEID_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('ENABLE_BOOKS', (SELECT CASE WHEN @ENABLEBOOKS_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('WHITE_GLOVE_CUSTOMER', (SELECT CASE WHEN @ENABLEWHITEGLOVECUSTOMER_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('AUTOCORRECT_PREVIOUS_PURCHASE', (SELECT CASE WHEN @ENABLE_AUTOCORRECT_PREVIOUS_PURCHASE_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE', (SELECT CASE WHEN @DISABLE_QUICKBOOKS_ONLINE_JOURNAL_NOTIFICATION_EXCLUDE_IP = 1 THEN 'TRUE' ELSE 'FALSE' END)),
// ('QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE', (SELECT CASE WHEN @DISABLE_QUICKBOOKS_ONLINE_PAYROLL_JOURNAL_NOTIFICATION_EXCLUDE_IP = 1 THEN 'TRUE' ELSE 'FALSE' END))   
  

// IF @ENABLEJOURNALPOSTING_IP = 1
// BEGIN
//  INSERT INTO #CONFIGKEYTABLE
//  VALUES (
//   'DISCOUNT_BY'
//   ,(
//    SELECT CASE
//      WHEN @DISCOUNTBY_IP = 1
//       THEN 'SALES'
//      WHEN @DISCOUNTBY_IP = 2
//       THEN 'DISCOUNT'
//      ELSE '0'
//      END
//    )
//   )
// END

// IF EXISTS (
//   SELECT 1
//   FROM [dbo].[XC_TENANT_CONFIG] WITH(NOLOCK)
//   WHERE TENANT_ID = @TENANT_ID_IP
//    AND CONFIG_KEY = N'ENABLE_PAYROLL'
//    AND CONFIG_VALUE <> (
//     SELECT CASE
//       WHEN @ENABLEPAYROLLSETUP_IP = 1
//        THEN 'TRUE'
//       ELSE 'FALSE'
//       END
//     )
//   )
// BEGIN
//  INSERT INTO #CONFIGKEYTABLE
//  VALUES (
//   'PAYROLL_DEACTIVATION_DATE'
//   ,(
//    SELECT CASE
//      WHEN @ENABLEPAYROLLSETUP_IP = 1
//       THEN null
//      ELSE CONVERT(VARCHAR(20), @GETDATE, 101)
//      END
//    )
//   )
// END



// BEGIN TRANSACTION trans

// BEGIN TRY

//  SET @TENANT_NAME_IP = LTRIM(RTRIM(@TENANT_NAME_IP))

//  UPDATE [DBO].[XC_TENANT]
//  SET TENANT_NAME = @TENANT_NAME_IP
//   , MODIFIED_ON = @GETDATE
//   , ISENABLECUSTOMCATEGORY = @CUSTOMCATEGORY_IP
//   , APPLICATION_TYPE = @APPTYPE_IP
//   , STARTDAY = @STARTDAY_IP
//   , ENABLE_EXTRACT = @EXTRACT_IP
//   , ENABLE_CREDITENTRY = @ENABLE_CREDITENTRY_IP
//   , GROUP_ID = @GROUP_ID_IP
//   , ISENABLECOST_CENTRE = @ENABLE_COST_CENTRE_IP
//   , PRODUCT_REVIEW_BY = @PRODUCT_REVIEW_BY_IP
//   , ENABLE_PAYMENT_PROCESSING = @ENABLEPAYMENTPROCESSING_IP
//   , ENABLE_STATEMENT_RECONCILIATION = @ENABLE_STATEMENT_RECONCILIATION_IP
//   , DISABLEONDEMANDEXTRACT = @DISABLEONDEMANDEXTRACT_IP
//   , ENABLE_CENTRALISED_INVOICE_PROCESSING = @ENABLE_CENTRALISED_INVOICE_PROCESSING_IP
//   , CENTRALISED_PROCESSING_LOCATION = @CENTRALISED_PROCESSING_LOCATION_IP
//   , ISENABLE_CENTRALISED_PROCESSING_LOCATION_ONLY = @ISENABLE_CENTRALISED_PROCESSING_LOCATION_ONLY_IP
//   , ACCOUNT_MANAGER = @XTRACHEFACCOUNTMANAGERID_IP
//   , IsSystemTenant = @SYSTEMTENANT_IP
//   , IsNonUSTenant = @NONUSTENANT_IP
//  WHERE TENANT_ID = @TENANT_ID_IP

//  IF EXISTS (
//    SELECT 1
//    FROM [DBO].[XC_LOCATION] WITH(NOLOCK)
//    WHERE TENENT_ID = @TENANT_ID_IP
//    )
//  BEGIN
//   UPDATE [DBO].[XC_LOCATION]
//   SET IS_CENTRALISED_PROCESSING_LOCATION = NULL
//   WHERE TENENT_ID = @TENANT_ID_IP
//    AND ISNULL(IS_CENTRALISED_PROCESSING_LOCATION, 0) > 0
//  END

//  IF EXISTS (
//    SELECT CASE
//      WHEN @CENTRALISED_PROCESSING_LOCATION_IP > 0
//       THEN 1
//      ELSE 0
//      END
//    )
//  BEGIN
//   UPDATE [DBO].[XC_LOCATION]
//   SET IS_CENTRALISED_PROCESSING_LOCATION = 1
//   WHERE TENENT_ID = @TENANT_ID_IP
//    AND LOCATION_ID = @CENTRALISED_PROCESSING_LOCATION_IP
//  END
//  ELSE
//  BEGIN
//   UPDATE [DBO].[XC_LOCATION]
//   SET IS_CENTRALISED_PROCESSING_LOCATION = 0
//   WHERE TENENT_ID = @TENANT_ID_IP
//    AND LOCATION_ID = @CENTRALISED_PROCESSING_LOCATION_IP
//  END

//  IF EXISTS (
//    SELECT 1
//    FROM [DBO].[XC_TENANT_CONFIG] WITH(NOLOCK)
//    WHERE TENANT_ID = @TENANT_ID_IP
//     AND CONFIG_KEY = 'ENABLE_APROVAL'
//    )
//  BEGIN
//   IF @ENABLE_APPROVAL_IP = 0
//   BEGIN
//    UPDATE [DBO].[XC_TENANT_RULES]
//    SET ACTIVE = 0
//     , MODIFIED_ON = @GETDATE
//    WHERE TENANT_ID = @TENANT_ID_IP
//     AND [STATUS] = 17
//   END
//  END

//  IF EXISTS (
//    SELECT 1
//    FROM [DBO].[XC_TENANT_CONFIG] WITH(NOLOCK)
//    WHERE TENANT_ID = @TENANT_ID_IP
//     AND CONFIG_KEY = 'ENABLE_QUICKBOOKS_LOCATIONINVOICE'
//    )
//  BEGIN
//   IF @ENABLE_QUICKBOOKS_LOCATIONINVOICE_IP <> (
//     SELECT CONFIG_VALUE
//     FROM [DBO].[XC_TENANT_CONFIG] WITH(NOLOCK)
//     WHERE TENANT_ID = @TENANT_ID_IP
//      AND CONFIG_KEY = 'ENABLE_QUICKBOOKS_LOCATIONINVOICE'
//     )
//   BEGIN
//    DELETE [DBO].[XC_QUICKBOOKS_CONFIG]
//    WHERE TENANT_ID = @TENANT_ID_IP

//	SELECT ID
//INTO #GLID
//FROM DBO.XC_TENANT_GLCODES WITH (NOLOCK)
//WHERE TENANTID = @TENANT_ID_IP

//UPDATE XTG
//SET XTG.QBO_REFERENCE_ID = NULL
//FROM DBO.XC_TENANT_GLCODES XTG
//INNER JOIN #GLID GI ON GI.ID = XTG.ID

//SELECT TENANT_VENDOR_ID
//INTO #VENDORID
//FROM DBO.XC_TENANT_VENDOR_MASTER WITH (NOLOCK)
//WHERE TENANT_ID = @TENANT_ID_IP

//UPDATE XTG
//SET XTG.QBO_REFERENCE_ID = NULL
//FROM DBO.XC_TENANT_VENDOR_MASTER XTG
//INNER JOIN #VENDORID GI ON GI.TENANT_VENDOR_ID = XTG.TENANT_VENDOR_ID

//SELECT Pk
//INTO #CLASSID
//FROM DBO.XC_TENANT_CLASS_MASTER WITH (NOLOCK)
//WHERE TenantId = @TENANT_ID_IP

//UPDATE XTG
//SET XTG.ReferenceId = NULL
//FROM DBO.XC_TENANT_CLASS_MASTER XTG
//INNER JOIN #CLASSID GI ON GI.Pk = XTG.Pk

//SELECT Pk
//INTO #CUSID
//FROM DBO.XC_TENANT_CUSTOMER_MASTER WITH (NOLOCK)
//WHERE TenantId = @TENANT_ID_IP

//UPDATE XTG
//SET XTG.QboReferenceId = NULL
//FROM DBO.XC_TENANT_CUSTOMER_MASTER XTG
//INNER JOIN #CUSID GI ON GI.Pk = XTG.Pk

//SELECT PAYMENT_ID
//INTO #PMID
//FROM DBO.XC_INVOICE_PAYMENT_MASTER WITH (NOLOCK)
//WHERE TENANT_ID = @TENANT_ID_IP

//UPDATE XTG
//SET XTG.QboReferenceId = NULL
//FROM DBO.XC_INVOICE_PAYMENT_MASTER XTG
//INNER JOIN #PMID GI ON GI.PAYMENT_ID = XTG.PAYMENT_ID

//SELECT PAYMENT_TERM_ID
//INTO #PTMID
//FROM DBO.xc_payment_terms_master WITH (NOLOCK)
//WHERE TENANT_ID = @TENANT_ID_IP

//UPDATE XTG
//SET XTG.RMS_REFERENCE_ID = NULL
//FROM DBO.xc_payment_terms_master XTG
//INNER JOIN #PTMID GI ON GI.PAYMENT_TERM_ID = XTG.PAYMENT_TERM_ID

//SELECT CONFIG_ID
//INTO #TCTEMP
//FROM DBO.XC_TENANT_CONFIG WITH (NOLOCK)
//WHERE TENANT_ID = @TENANT_ID_IP
//	AND CONFIG_KEY IN (
//		'QBO_GL_MODIFIED_DATE'
//		,'QBO_VENDOR_MODIFIED_DATE'
//		,'QBO_CLASS_MODIFIED_DATE'
//		,'QBO_PAYMENT_TERM_MODIFIED_DATE'
//		,'QBO_CUSTOMER_MODIFIED_DATE'
//		,'QBO_PAYMENT_METHOD_MODIFIED_DATE'
//		)

//UPDATE XTC
//SET config_value = NULL
//FROM XC_TENANT_CONFIG XTC
//INNER JOIN #TCTEMP T ON T.CONFIG_ID = XTC.CONFIG_ID

//    INSERT INTO [DBO].[XC_AUDIT_XTRACHEF](
//     [Guid]
//     , Internal
//     , Severity
//     , EntityId
//     , EntityStatus
//     , Created
//     , CreatedBy
//     , [Description]
//     , [Type]
//     , EntityType
//     , [Json]
//     )
//    VALUES(
//     NewID()
//     , 1
//     , 50
//     , @TENANT_ID_IP
//     , 'update'
//     , @GETDATE
//     , 0
//     , CASE
//      WHEN @ENABLE_QUICKBOOKS_LOCATIONINVOICE_IP = 1
//       THEN 'Quickbooks location level configuration enabled '
//      ELSE 'Quickbooks location level configuration disabled'
//      END
//     , 'UPDATE'
//     , 'TenantSetting'
//     , NULL
//     )
//   END
//  END

//  IF @IS_LOCATION_CONFIG_TO_BE_CHANGED_IP = 1
//  BEGIN
//   UPDATE [DBO].[XC_LOCATION_CONFIGS]
//   SET CONFIG_VALUE = NULL
//    , MODIFIED_ON = @GETDATE
//   WHERE TENANT_ID = @TENANT_ID_IP
//    AND CONFIG_KEY = 'UPLOAD_TRIAL_END_ON'
//  END

//  UPDATE XTC
//  SET XTC.CONFIG_VALUE = CKT.CONFIG_VALUE
//   , XTC.MODIFIED_ON = @GETDATE
//  FROM [DBO].[XC_TENANT_CONFIG] XTC
//  INNER JOIN #CONFIGKEYTABLE CKT ON XTC.CONFIG_KEY = CKT.CONFIG_KEY
//  WHERE XTC.TENANT_ID = @TENANT_ID_IP

//  INSERT INTO [DBO].[XC_TENANT_CONFIG](
//   TENANT_ID
//   , CONFIG_KEY
//   , CONFIG_VALUE
//   , CREATED_ON
//   , MODIFIED_ON
//   , CONFIG_VALUE_DESCRIPTION
//   )
//  SELECT @TENANT_ID_IP
//   , CKT.CONFIG_KEY
//   , CKT.CONFIG_VALUE
//   , @GETDATE
//   , @GETDATE
//   , NULL
//  FROM #CONFIGKEYTABLE CKT
//  LEFT JOIN [DBO].[XC_TENANT_CONFIG] XCTC WITH(NOLOCK) ON CKT.CONFIG_KEY = XCTC.CONFIG_KEY
//   AND XCTC.TENANT_ID = @TENANT_ID_IP
//  WHERE XCTC.CONFIG_KEY IS NULL

//  INSERT INTO [DBO].[XC_AUDIT_TENANT_CONFIG]
//  SELECT @GETDATE
//   ,'Config Updated'
//   , @USER_ID_IP
//   , @BROWSER_IP
//   , @VERSION_IP
//   , @TENANT_ID_IP
//   , CONFIG_KEY
//   , CONFIG_VALUE
//   , @GETDATE
//   , @GETDATE
//   , NULL
//  FROM #CONFIGKEYTABLE


//  IF (
//    @PRODUCT_REVIEW_BY_IP IN (
//     1
//     ,3
//     )
//    AND @IS_PRODUCT_REVIEW_PREVIOUS IN (
//     4
//     ,2
//     )
//    )
//  BEGIN
//   UPDATE [DBO].[XC_PRODUCT_MASTER_EXTENDED]
//   SET IS_NEWPRODUCT = 1
//    , IS_INVENTORY_REVIEWED = NULL
//   WHERE TENANT_ID = @TENANT_ID_IP


//   SELECT @PRODUCT_ID = COALESCE(@PRODUCT_ID + ',', '') + CAST(PRODUCT_ID AS VARCHAR(MAX))
//    , @PRODUCT_COUNT = COALESCE(1 + @PRODUCT_COUNT, 1)
//   FROM [DBO].[XC_PRODUCT_MASTER_EXTENDED] WITH(NOLOCK)
//   WHERE TENANT_ID = @TENANT_ID_IP

//   INSERT INTO [DBO].[XC_AUDIT_XTRACHEF](
//    [Guid]
//    , Internal
//    , Severity
//    , EntityId
//    , EntityStatus
//    , Created
//    , CreatedBy
//    , [Description]
//    , [Type]
//    , EntityType
//    , [Json]
//    )
//   VALUES(
//    NewID()
//    , 1
//    , 50
//    , @TENANT_ID_IP
//    , 'update'
//    , @GETDATE
//    , @USER_ID_IP
//    , CONCAT(
//     'Product reviewed by changed to '
//     , @PRODUCT_REVIEW_BY_IP
//     , ', '
//     , @PRODUCT_COUNT
//     , ' products are cleared from Inventory verification queue'
//     )
//    , 'UPDATE'
//    , 'TenantSetting'
//    , @PRODUCT_ID
//    )

//  END

//  IF EXISTS (
//    SELECT 1
//    FROM [DBO].[XC_TENANT_CONFIG] WITH(NOLOCK)
//    WHERE CONFIG_KEY = 'QUICKBOOK_EXTRACT'
//     AND CONFIG_VALUE = 'TRUE'
//     AND TENANT_ID = @TENANT_ID_IP
//    )
//  BEGIN
//   IF NOT EXISTS (
//     SELECT 1
//     FROM [DBO].[XC_TENANT_CONFIG] WITH(NOLOCK)
//     WHERE CONFIG_KEY = 'QUICKBOOK_APPLY_HEADER_LEVEL_AMOUNT'
//      AND TENANT_ID = @TENANT_ID_IP
//     )
//   BEGIN
//    INSERT INTO [DBO].[XC_TENANT_CONFIG](
//     TENANT_ID
//     , CONFIG_KEY
//     , CONFIG_VALUE
//     , CREATED_ON
//     , MODIFIED_ON
//     , CONFIG_VALUE_DESCRIPTION
//     )
//    VALUES(
//     @TENANT_ID_IP
//     , 'QUICKBOOK_APPLY_HEADER_LEVEL_AMOUNT'
//     , 'GROUP_DIST_GL'
//     , @GETDATE
//     , @GETDATE
//     , NULL
//     )
//   END
//  END

//  IF @ENABLE_BILL_PAY_IP = 1
//  BEGIN
//   IF NOT EXISTS (SELECT 1 FROM [dbo].[XC_TENANT_ACCESS_PACKAGE] WITH(NOLOCK) WHERE TenantId = @TENANT_ID_IP AND PackageCode = 'XC_ADD_BANKING')
//   BEGIN
//    INSERT INTO [dbo].[XC_TENANT_ACCESS_PACKAGE] VALUES(@TENANT_ID_IP, 0, 'XC_ADD_BANKING', @GETDATE, 1, @GETDATE, 1)
//   END
//  END
//  ELSE
//  BEGIN
//   IF EXISTS (SELECT 1 FROM [dbo].[XC_TENANT_ACCESS_PACKAGE] WITH(NOLOCK) WHERE TenantId = @TENANT_ID_IP AND PackageCode = 'XC_ADD_BANKING')
//   BEGIN
//    DELETE FROM [dbo].[XC_TENANT_ACCESS_PACKAGE] WHERE TenantId = @TENANT_ID_IP AND PackageCode = 'XC_ADD_BANKING'
//   END
//  END

//  IF @@TRANCOUNT > 0
//  BEGIN
//   COMMIT TRANSACTION trans
//  END
// END TRY

// BEGIN CATCH
//  SELECT @ErrorMessage = ERROR_MESSAGE()
//   , @ErrorSeverity = ERROR_SEVERITY()
//   , @ErrorState = ERROR_STATE()

//  IF @@TRANCOUNT > 0
//  BEGIN
//   ROLLBACK TRANSACTION trans

//   RAISERROR (
//     @ErrorMessage
//     , @ErrorSeverity
//     , @ErrorState
//     )
//  END
// END CATCH

// DROP TABLE IF EXISTS #CONFIGKEYTABLE
// DROP TABLE IF EXISTS #GLID
// DROP TABLE IF EXISTS #VENDORID
// DROP TABLE IF EXISTS #CLASSID
// DROP TABLE IF EXISTS #CUSID
// DROP TABLE IF EXISTS #PMID
// DROP TABLE IF EXISTS #PTMID
// DROP TABLE IF EXISTS #TCTEMP

//END
//GO